name: Lint
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Shellcheck and Shell Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: asdf_install
        uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1
      - name: Shellcheck
        run: shellcheck -x bin/* -P lib/
      - name: Shell Format - List files to check
        run: shfmt -f .
      - name: Shell Format - Validate
        run: shfmt -d -i 2 -ci .
