name: Lint
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    name: Shellcheck and Shell Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: asdf_install
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
      - name: Shellcheck
        run: shellcheck -x bin/* -P lib/
      - name: Shell Format - List files to check
        run: shfmt -f .
      - name: Shell Format - Validate
        run: shfmt -d -i 2 -ci .
